import { withBase } from "./basePath";

export const siteConfig = {
  recipientName: "Ani",
  pageTitle: "For Ani",
  escapePageTitle: "Black Hole Escape",
  ticketGatePageTitle: "Tomt Univers",
  mainPageTitle: "Adi Expedition 33",
  gestralBriefingPageTitle: "Gestral Briefing // Adi Expedition 33",
  campMissionPageTitle: "Camp // Esquie",
  badunkadunkVaultPageTitle: "Badunkadunk Vault // Nevron",
  finalMissionPageTitle: "Francois Throne // Finale",
  valentineCongratsPageTitle: "Valentinsdag // Fra Adi",
  mainWorldName: "Adi Expedition 33",
  escapeRoomPath: withBase("/black-hole"),
  ticketGatePath: withBase("/tomt-univers"),
  mainPagePath: withBase("/hovedside"),
  campMissionPath: withBase("/hovedside/camp"),
  badunkadunkVaultPath: withBase("/hovedside/badunkadunk-vault"),
  finalMissionPath: withBase("/hovedside/francois-throne"),
  valentineCongratsPath: withBase("/hovedside/valentines-hilsen"),
  continueButtonLabel: "Trykk for a krysse horisonten",
  escapeCompletedStorageKey: "ani_escape_completed",
  accessTicketStorageKey: "ani_escape_ticket_granted",
  gestralStoneGrantedStorageKey: "ani_gestral_stone_granted",
  campMissionCompletedStorageKey: "ani_camp_mission_completed",
  vaultMissionCompletedStorageKey: "ani_vault_mission_completed",
  finalMissionCompletedStorageKey: "ani_final_mission_completed",
  introWarpDurationMs: 1400,
  enableDevEscapeSkip: true
} as const;
